<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN00119" ignored="2" name="AutomationTesting" tests="2" failures="1" timestamp="22 Apr 2019 07:40:41 GMT" time="68.816" errors="0">
  <testcase name="login" time="2.325" classname="com.automation.testCases.TC_LoginDDT_002"/>
  <testcase name="addCustDetails" time="42.892" classname="com.automation.testCases.TC_AddCustomer_003">
    <failure type="java.lang.AssertionError" message="expected [Customer Registered Successfully123!!!] but found [Customer Registered Successfully!!!]">
      <![CDATA[java.lang.AssertionError: expected [Customer Registered Successfully123!!!] but found [Customer Registered Successfully!!!]
at com.automation.testCases.TC_AddCustomer_003.addCustDetails(TC_AddCustomer_003.java:33)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addCustDetails -->
  <testcase name="@AfterTest tearDown" time="0.0" classname="com.automation.testCases.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase name="@BeforeTest setUp" time="0.0" classname="com.automation.testCases.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeTest setUp -->
</testsuite> <!-- AutomationTesting -->
